version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - pip install -Ur requirements.txt
      - npm install -g aws-cdk@2.1013.0
  pre_build:
    commands:
      - mkdir -p reports
      - black . --exclude '.venv' --check --skip-string-normalization
      - pytest --cov --junitxml=reports/pytest.xml --cov-report xml:reports/coverage.xml
  build:
    commands:
      - cdk synth iac-demo > $CODEBUILD_SRC_DIR/template_iac-demo.yml
      - cfn-lint $CODEBUILD_SRC_DIR/template_iac-demo.yml -i W3005 -f junit > reports/cfn-lint_iac-demo.xml

      - cdk synth iac-demo-pipeline > $CODEBUILD_SRC_DIR/template_iac-demo-pipeline.yml
      - cfn-lint $CODEBUILD_SRC_DIR/template_iac-demo-pipeline.yml -i W3005 -f junit > reports/cfn-lint_iac-demo-pipeline.xml
artifacts:
  files:
    - "**/*"
reports:
  Tests:
    base-directory: ./reports
    file-format: JUNITXML
    files:
      - pytest.xml
      - cfn-lint_iac-demo.xml
      - cfn-lint_iac-demo-pipeline.xml
  Coverage:
    base-directory: ./reports
    file-format: COBERTURAXML
    files:
      - coverage.xml
